name: Streamlit App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit
        pip install -r requirements.txt
        
    - name: Install Ollama
      run: |
        pip install ollama

    - name: Download Model
      run: |
        # Command to download the model, this will depend on Ollama's CLI or API
        ollama download llama3

    - name: Run tests
      run: |
        pytest -v
